### ISSUE TITLE
UAT README

### ISSUE THREAD

**Issue by davbt** [Monash-FIT3170/CUMA#9]
Hosted site: [REDACTED]

Google Form: [REDACTED]

Env file: [REDACTED]

**Comment by ZileiChen** [comment]
**Sign Up with personal/non-Monash Account with MFA**
1. On login page, click “Sign Up”
2. Fill the sign up form
3. After signing up, you’ll be prompted to enable MFA, click on “Enable MFA”
4. Install Google or Microsoft Authentication 
5. Scan the QR code with your Auth app, and follow the instructions
6. Once Sign Up and MFA is complete, logout and then check if you can login


**Log In with personal/non-Monash Account with MFA**
1. On login page, fill up your email and password
2. You will be redirected to input an MFA code
3. Open your Authentication application (e.g. Google Authentication)
4. Input the code to the website

**Log In/ Sign Up with Google Account**
1. On login/sign up page, click “Continue/Signup with Google” button
2. Login with your monash email, ensuring the domain is @student.monash.edu
3. Google will redirect you to Monash authentication to login with you monash account (only works for fresh google login try in incognito)
4. After Monash has authenticated, it will redirect to the index page of the website


**Add Unit Via _Add Unit Page_**
1. Click “Add Unit” button
2. Create a new unit with the Unit Code being “DEMO_” + <your-first-name> + “_” <your-fav-monash-unit> (e.g. DEMO_Jake_FIT3077). Fill the remaining fields with appropriate data
3.  Click “Add unit to Course”
4.  Check if you can now view your unit on the home page. Ensure other test users can also see your unit.

**Add Unit Connections** 
1. Search for your created unit from last test on Home page
2. Click on your unit
3. Click “Add Unit connection” on the centre column
4. Click “Add to Existing Unit” on the last column
5.  Choose a random foreign unit
6.  Click “OK” for adding unit connection
7. Check if you can see the unit connection after searching and clicking your original unit on the home page 

**Send Unit Connections**
1. After adding at least one unit connection, click the “Send Connections” button on the Nav Bar
2. Check if this opens your default mail application, where the email’s contents are populated with your unit connections

**Search For Units**
1. Navigate to the Mapping tab
2. Search for a unit within Bachelors of Software Engineering
3. Check if the search function is working correctly

**Comment by dtonda8** [comment]
https://drive.google.com/file/d/1e6VIRL7H7DyVEynzhhJdyUZeMOqH9g1s/view?usp=sharing

rename to `.env`

**Comment by maddyyy0110** [comment]
completed
